accounts:
- prodman/accounts/*
- prodman/controllers/accounts_controller.py
- prodman/controllers/taxes_and_totals.py

stock:
- prodman/stock/*
- prodman/controllers/stock_controller.py
- prodman/controllers/item_variant.py

assets:
- prodman/assets/*

regional:
- prodman/regional/*

selling:
- prodman/selling/*
- prodman/controllers/selling_controller.py

buying:
- prodman/buying/*
- prodman/controllers/buying_controller.py

support:
- prodman/support/*

POS:
- pos*

ecommerce:
- prodman/e_commerce/*

maintenance:
- prodman/maintenance/*

manufacturing:
- prodman/manufacturing/*

crm:
- prodman/crm/*

HR:
- prodman/hr/*

payroll:
- prodman/payroll*

projects:
- prodman/projects/*

# Any python files modifed but no test files modified
needs-tests:
- any: ['prodman/**/*.py']
  all: ['!prodman/**/test*.py']
